const emojiDict = {
    // Smileys & People
    "grinning face": "😀",
    "grinning face with big eyes": "😃",
    "grinning face with smiling eyes": "😄",
    "beaming face with smiling eyes": "😁",
    "grinning squinting face": "😆",
    "grinning face with sweat": "😅",
    "rolling on the floor laughing": "🤣",
    "face with tears of joy": "😂",
    "slightly smiling face": "🙂",
    "upside-down face": "🙃",
    "winking face": "😉",
    "smiling face with smiling eyes": "😊",
    "smiling face with halo": "😇",
    "smiling face with hearts": "🥰",
    "smiling face with heart-eyes": "😍",
    "star-struck": "🤩",
    "face blowing a kiss": "😘",
    "kissing face": "😗",
    "smiling face": "☺️",
    "kissing face with closed eyes": "😚",
    "kissing face with smiling eyes": "😙",
    "smiling face with tear": "🥲",
    "face savoring food": "😋",
    "face with tongue": "😛",
    "winking face with tongue": "😜",
    "zany face": "🤪",
    "squinting face with tongue": "😝",
    "money-mouth face": "🤑",
    "smiling face with open hands": "🤗",
    "face with hand over mouth": "🤭",
    "shushing face": "🤫",
    "thinking face": "🤔",
    "zipper-mouth face": "🤐",
    "face with raised eyebrow": "🤨",
    "neutral face": "😐",
    "expressionless face": "😑",
    "face without mouth": "😶",
    "face in clouds": "😶‍🌫️",
    "smirking face": "😏",
    "unamused face": "😒",
    "face with rolling eyes": "🙄",
    "grimacing face": "😬",
    "face exhaling": "😮‍💨",
    "lying face": "🤥",
    "relieved face": "😌",
    "pensive face": "😔",
    "sleepy face": "😪",
    "drooling face": "🤤",
    "sleeping face": "😴",
    "face with medical mask": "😷",
    "face with thermometer": "🤒",
    "face with head-bandage": "🤕",
    "nauseated face": "🤢",
    "face vomiting": "🤮",
    "sneezing face": "🤧",
    "hot face": "🥵",
    "cold face": "🥶",
    "woozy face": "🥴",
    "face with crossed-out eyes": "😵",
    "face with spiral eyes": "😵‍💫",
    "exploding head": "🤯",
    "cowboy hat face": "🤠",
    "partying face": "🥳",
    "disguised face": "🥸",
    "smiling face with sunglasses": "😎",
    "nerd face": "🤓",
    "face with monocle": "🧐",
    "confused face": "😕",
    "worried face": "😟",
    "slightly frowning face": "🙁",
    "frowning face": "☹️",
    "face with open mouth": "😮",
    "hushed face": "😯",
    "astonished face": "😲",
    "flushed face": "😳",
    "pleading face": "🥺",
    "frowning face with open mouth": "😦",
    "anguished face": "😧",
    "fearful face": "😨",
    "anxious face with sweat": "😰",
    "sad but relieved face": "😥",
    "crying face": "😢",
    "loudly crying face": "😭",
    "face screaming in fear": "😱",
    "confounded face": "😖",
    "persevering face": "😣",
    "disappointed face": "😞",
    "downcast face with sweat": "😓",
    "weary face": "😩",
    "tired face": "😫",
    "yawning face": "🥱",
    "face with steam from nose": "😤",
    "enraged face": "😡",
    "angry face": "😠",
    "face with symbols on mouth": "🤬",
    "smiling face with horns": "😈",
    "angry face with horns": "👿",
    "skull": "💀",
    "skull and crossbones": "☠️",
    "pile of poo": "💩",
    "clown face": "🤡",
    "ogre": "👹",
    "goblin": "👺",
    "ghost": "👻",
    "alien": "👽",
    "alien monster": "👾",
    "robot": "🤖",
    "grinning cat": "😺",
    "grinning cat with smiling eyes": "😸",
    "cat with tears of joy": "😹",
    "smiling cat with heart-eyes": "😻",
    "cat with wry smile": "😼",
    "kissing cat": "😽",
    "weary cat": "🙀",
    "crying cat": "😿",
    "pouting cat": "😾",
    "kiss mark": "💋",
    "waving hand": "👋",
    "raised back of hand": "🤚",
    "hand with fingers splayed": "🖐️",
    "raised hand": "✋",
    "vulcan salute": "🖖",
    "pinched fingers": "👌",
    "pinching hand": "🤏",
    "victory hand": "✌️",
    "crossed fingers": "🤞",
    "love-you gesture": "🤟",
    "sign of the horns": "🤘",
    "call me hand": "🤙",
    "backhand index pointing left": "👈",
    "backhand index pointing right": "👉",
    "backhand index pointing up": "👆",
    "middle finger": "🖕",
    "backhand index pointing down": "👇",
    "index pointing up": "☝️",
    "thumbs up": "👍",
    "thumbs down": "👎",
    "raised fist": "✊",
    "oncoming fist": "👊",
    "left-facing fist": "🤛",
    "right-facing fist": "🤜",
    "clapping hands": "👏",
    "raising hands": "🙌",
    "open hands": "👐",
    "palms up together": "🤲",
    "handshake": "🤝",
    "folded hands": "🙏",
    "writing hand": "✍️",
    "nail polish": "💅",
    "selfie": "🤳",
    "flexed biceps": "💪",
    "mechanical arm": "🦾",
    "mechanical leg": "🦿",
    "leg": "🦵",
    "foot": "🦶",
    "ear": "👂",
    "ear with hearing aid": "🦻",
    "nose": "👃",
    "brain": "🧠",
    "anatomical heart": "🫀",
    "lungs": "🫁",
    "tooth": "🦷",
    "bone": "🦴",
    "eyes": "👀",
    "eye": "👁️",
    "tongue": "👅",
    "mouth": "👄",
    "baby": "👶",
    "child": "🧒",
    "boy": "👦",
    "girl": "👧",
    "person": "🧑",
    "person: blond hair": "👱",
    "man": "👨",
    "person: beard": "🧔",
    "man: red hair": "👨‍🦰",
    "man: curly hair": "👨‍🦱",
    "man: white hair": "👨‍🦳",
    "man: bald": "👨‍🦲",
    "woman": "👩",
    "woman: red hair": "👩‍🦰",
    "person: red hair": "🧑‍🦰",
    "woman: curly hair": "👩‍🦱",
    "person: curly hair": "🧑‍🦱",
    "woman: white hair": "👩‍🦳",
    "person: white hair": "🧑‍🦳",
    "woman: bald": "👩‍🦲",
    "person: bald": "🧑‍🦲",
    "♀️ woman: blond hair": "👱‍♀️",
    "♂️ man: blond hair": "👱‍♂️",
    "older person": "🧓",
    "old man": "👴",
    "old woman": "👵",
    "person frowning": "🙍",
    "♂️ man frowning": "🙍‍♂️",
    "♀️ woman frowning": "🙍‍♀️",
    "person pouting": "🙎",
    "♂️ man pouting": "🙎‍♂️",
    "♀️ woman pouting": "🙎‍♀️",
    "person gesturing no": "🙅",
    "♂️ man gesturing no": "🙅‍♂️",
    "♀️ woman gesturing no": "🙅‍♀️",
    "person gesturing ok": "🙆",
    "♂️ man gesturing ok": "🙆‍♂️",
    "♀️ woman gesturing ok": "🙆‍♀️",
    "person tipping hand": "💁",
    "♂️ man tipping hand": "💁‍♂️",
    "♀️ woman tipping hand": "💁‍♀️",
    "person raising hand": "🙋",
    "♂️ man raising hand": "🙋‍♂️",
    "♀️ woman raising hand": "🙋‍♀️",
    "deaf person": "🧏",
    "♂️ deaf man": "🧏‍♂️",
    "♀️ deaf woman": "🧏‍♀️",
    "person bowing": "🙇",
    "♂️ man bowing": "🙇‍♂️",
    "♀️ woman bowing": "🙇‍♀️",
    "person facepalming": "🤦",
    "♂️ man facepalming": "🤦‍♂️",
    "♀️ woman facepalming": "🤦‍♀️",
    "person shrugging": "🤷",
    "♂️ man shrugging": "🤷‍♂️",
    "♀️ woman shrugging": "🤷‍♀️",
    "health worker": "🧑‍⚕️",
    "man health worker": "👨‍⚕️",
    "woman health worker": "👩‍⚕️",
    "student": "🧑‍🎓",
    "man student": "👨‍🎓",
    "woman student": "👩‍🎓",
    "teacher": "🧑‍🏫",
    "man teacher": "👨‍🏫",
    "woman teacher": "👩‍🏫",
    "judge": "🧑‍⚖️",
    "man judge": "👨‍⚖️",
    "woman judge": "👩‍⚖️",
    "farmer": "🧑‍🌾",
    "man farmer": "👨‍🌾",
    "woman farmer": "👩‍🌾",
    "cook": "🧑‍🍳",
    "man cook": "👨‍🍳",
    "woman cook": "👩‍🍳",
    "mechanic": "🧑‍🔧",
    "man mechanic": "👨‍🔧",
    "woman mechanic": "👩‍🔧",
    "factory worker": "🧑‍🏭",
    "man factory worker": "👨‍🏭",
    "woman factory worker": "👩‍🏭",
    "office worker": "🧑‍💼",
    "man office worker": "👨‍💼",
    "woman office worker": "👩‍💼",
    "scientist": "🧑‍🔬",
    "man scientist": "👨‍🔬",
    "woman scientist": "👩‍🔬",
    "technologist": "🧑‍💻",
    "man technologist": "👨‍💻",
    "woman technologist": "👩‍💻",
    "singer": "🧑‍🎤",
    "man singer": "👨‍🎤",
    "woman singer": "👩‍🎤",
    "artist": "🧑‍🎨",
    "man artist": "👨‍🎨",
    "woman artist": "👩‍🎨",
    "pilot": "🧑‍✈️",
    "man pilot": "👨‍✈️",
    "woman pilot": "👩‍✈️",
    "astronaut": "🧑‍🚀",
    "man astronaut": "👨‍🚀",
    "woman astronaut": "👩‍🚀",
    "firefighter": "🧑‍🚒",
    "man firefighter": "👨‍🚒",
    "woman firefighter": "👩‍🚒",
    "police officer": "👮",
    "man police officer": "👮‍♂️",
    "woman police officer": "👮‍♀️",
    "detective": "🕵️",
    "man detective": "🕵️‍♂️",
    "woman detective": "🕵️‍♀️",
    "guard": "💂",
    "man guard": "💂‍♂️",
    "woman guard": "💂‍♀️",
    "ninja": "🥷",
    "construction worker": "👷",
    "man construction worker": "👷‍♂️",
    "woman construction worker": "👷‍♀️",
    "prince": "🤴",
    "princess": "👸",
    "person wearing turban": "👳",
    "man wearing turban": "👳‍♂️",
    "woman wearing turban": "👳‍♀️",
    "person with skullcap": "👲",
    "woman with headscarf": "🧕",
    "person in tuxedo": "🤵",
    "man in tuxedo": "🤵‍♂️",
    "woman in tuxedo": "🤵‍♀️",
    "person with veil": "👰",
    "man with veil": "👰‍♂️",
    "woman with veil": "👰‍♀️",
    "pregnant woman": "🤰",
    "breast-feeding": "🤱",
    "woman feeding baby": "👩‍🍼",
    "man feeding baby": "👨‍🍼",
    "person feeding baby": "🧑‍🍼",
    "baby angel": "👼",
    "santa claus": "🎅",
    "mrs. claus": "🤶",
    "mx claus": "🧑‍🎄",
    "superhero": "🦸",
    "man superhero": "🦸‍♂️",
    "woman superhero": "🦸‍♀️",
    "supervillain": "🦹",
    "man supervillain": "🦹‍♂️",
    "woman supervillain": "🦹‍♀️",
    "mage": "🧙",
    "man mage": "🧙‍♂️",
    "woman mage": "🧙‍♀️",
    "fairy": "🧚",
    "man fairy": "🧚‍♂️",
    "woman fairy": "🧚‍♀️",
    "vampire": "🧛",
    "man vampire": "🧛‍♂️",
    "woman vampire": "🧛‍♀️",
    "merperson": "🧜",
    "merman": "🧜‍♂️",
    "mermaid": "🧜‍♀️",
    "elf": "🧝",
    "man elf": "🧝‍♂️",
    "woman elf": "🧝‍♀️",
    "genie": "🧞",
    "man genie": "🧞‍♂️",
    "woman genie": "🧞‍♀️",
    "zombie": "🧟",
    "man zombie": "🧟‍♂️",
    "woman zombie": "🧟‍♀️",
    "person getting massage": "💆",
    "man getting massage": "💆‍♂️",
    "woman getting massage": "💆‍♀️",
    "person getting haircut": "💇",
    "man getting haircut": "💇‍♂️",
    "woman getting haircut": "💇‍♀️",
    "person walking": "🚶",
    "man walking": "🚶‍♂️",
    "woman walking": "🚶‍♀️",
    "person standing": "🧍",
    "man standing": "🧍‍♂️",
    "woman standing": "🧍‍♀️",
    "person kneeling": "🧎",
    "man kneeling": "🧎‍♂️",
    "woman kneeling": "🧎‍♀️",
    "person with white cane": "🧑‍🦯",
    "man with white cane": "👨‍🦯",
    "woman with white cane": "👩‍🦯",
    "person in motorized wheelchair": "🧑‍🦼",
    "man in motorized wheelchair": "👨‍🦼",
    "woman in motorized wheelchair": "👩‍🦼",
    "person in manual wheelchair": "🧑‍🦽",
    "man in manual wheelchair": "👨‍🦽",
    "woman in manual wheelchair": "👩‍🦽",
    "person running": "🏃",
    "man running": "🏃‍♂️",
    "woman running": "🏃‍♀️",
    "woman dancing": "💃",
    "man dancing": "🕺",
    "person in suit levitating": "🕴️",
    "people with bunny ears": "👯",
    "men with bunny ears": "👯‍♂️",
    "women with bunny ears": "👯‍♀️",
    "person in steamy room": "🧖",
    "man in steamy room": "🧖‍♂️",
    "woman in steamy room": "🧖‍♀️",
    "person in lotus position": "🧘",
    "people holding hands": "🧑‍🤝‍🧑",
    "women holding hands": "👭",
    "woman and man holding hands": "👫",
    "men holding hands": "👬",
    "kiss": "💏",
    "kiss: woman, man": "👩‍❤️‍💋‍👨",
    "kiss: man, man": "👨‍❤️‍💋‍👨",
    "kiss: woman, woman": "👩‍❤️‍💋‍👩",
    "couple with heart": "💑",
    "couple with heart: woman, man": "👩‍❤️‍👨",
    "couple with heart: man, man": "👨‍❤️‍👨",
    "couple with heart: woman, woman": "👩‍❤️‍👩",
    "family": "👪",
    "family: man, woman, boy": "👨‍👩‍👦",
    "family: man, woman, girl": "👨‍👩‍👧",
    "family: man, woman, girl, boy": "👨‍👩‍👧‍👦",
    "family: man, woman, boy, boy": "👨‍👩‍👦‍👦",
    "family: man, woman, girl, girl": "👨‍👩‍👧‍👧",
    "family: man, man, boy": "👨‍👨‍👦",
    "family: man, man, girl": "👨‍👨‍👧",
    "family: man, man, girl, boy": "👨‍👨‍👧‍👦",
    "family: man, man, boy, boy": "👨‍👨‍👦‍👦",
    "family: man, man, girl, girl": "👨‍👨‍👧‍👧",
    "family: woman, woman, boy": "👩‍👩‍👦",
    "family: woman, woman, girl": "👩‍👩‍👧",
    "family: woman, woman, girl, boy": "👩‍👩‍👧‍👦",
    "family: woman, woman, boy, boy": "👩‍👩‍👦‍👦",
    "family: woman, woman, girl, girl": "👩‍👩‍👧‍👧",
    "family: man, boy": "👨‍👦",
    "family: man, boy, boy": "👨‍👦‍👦",
    "family: man, girl": "👨‍👧",
    "family: man, girl, boy": "👨‍👧‍👦",
    "family: man, girl, girl": "👨‍👧‍👧",
    "family: woman, boy": "👩‍👦",
    "family: woman, boy, boy": "👩‍👦‍👦",
    "family: woman, girl": "👩‍👧",
    "family: woman, girl, boy": "👩‍👧‍👦",
    "family: woman, girl, girl": "👩‍👧‍👧",
    "speaking head": "🗣️",
    "bust in silhouette": "👤",
    "busts in silhouette": "👥",
    "people hugging": "🫂",
    "footprints": "👣",
    "luggage": "🧳",
    "closed umbrella": "🌂",
    "umbrella": "☂️",
    "jack-o-lantern": "🎃",
    "thread": "🧵",
    "yarn": "🧶",
    "glasses": "👓",
    "sunglasses": "🕶️",
    "goggles": "🥽",
    "lab coat": "🥼",
    "safety vest": "🦺",
    "necktie": "👔",
    "t-shirt": "👕",
    "jeans": "👖",
    "scarf": "🧣",
    "gloves": "🧤",
    "coat": "🧥",
    "socks": "🧦",
    "dress": "👗",
    "kimono": "👘",
    "sari": "🥻",
    "one-piece swimsuit": "🩱",
    "briefs": "🩲",
    "shorts": "🩳",
    "bikini": "👙",
    "woman’s clothes": "👚",
    "purse": "👛",
    "handbag": "👜",
    "clutch bag": "👝",
    "backpack": "🎒",
    "thong sandal": "🩴",
    "man’s shoe": "👞",
    "running shoe": "👟",
    "hiking boot": "🥾",
    "flat shoe": "🥿",
    "high-heeled shoe": "👠",
    "woman’s sandal": "👡",
    "ballet shoes": "🩰",
    "woman’s boot": "👢",
    "crown": "👑",
    "woman’s hat": "👒",
    "top hat": "🎩",
    "graduation cap": "🎓",
    "billed cap": "🧢",
    "military helmet": "🪖",
    "rescue worker’s helmet": "⛑️",
    "lipstick": "💄",
    "ring": "💍",
    "briefcase": "💼",
    "drop of blood": "🩸",
    // Animals & Nature
    "see-no-evil monkey": "🙈",
    "hear-no-evil monkey": "🙉",
    "speak-no-evil monkey": "🙊",
    "collision": "💥",
    "dizzy": "💫",
    "sweat droplets": "💦",
    "dashing away": "💨",
    "monkey face": "🐵",
    "monkey": "🐒",
    "gorilla": "🦍",
    "orangutan": "🦧",
    "dog face": "🐶",
    "‍🦺 service dog": "🐕",
    "guide dog": "🦮",
    "poodle": "🐩",
    "wolf": "🐺",
    "fox": "🦊",
    "raccoon": "🦝",
    "cat face": "🐱",
    "‍⬛ black cat": "🐈",
    "lion": "🦁",
    "tiger face": "🐯",
    "tiger": "🐅",
    "leopard": "🐆",
    "horse face": "🐴",
    "horse": "🐎",
    "unicorn": "🦄",
    "zebra": "🦓",
    "deer": "🦌",
    "bison": "🦬",
    "cow face": "🐮",
    "ox": "🐂",
    "water buffalo": "🐃",
    "cow": "🐄",
    "pig face": "🐷",
    "pig": "🐖",
    "boar": "🐗",
    "pig nose": "🐽",
    "ram": "🐏",
    "ewe": "🐑",
    "goat": "🐐",
    "camel": "🐪",
    "two-hump camel": "🐫",
    "llama": "🦙",
    "giraffe": "🦒",
    "elephant": "🐘",
    "mammoth": "🦣",
    "rhinoceros": "🦏",
    "hippopotamus": "🦛",
    "mouse face": "🐭",
    "mouse": "🐁",
    "rat": "🐀",
    "hamster": "🐹",
    "rabbit face": "🐰",
    "rabbit": "🐇",
    "️ chipmunk": "🐿",
    "beaver": "🦫",
    "hedgehog": "🦔",
    "bat": "🦇",
    "‍❄️ polar bear": "🐻",
    "koala": "🐨",
    "panda": "🐼",
    "sloth": "🦥",
    "otter": "🦦",
    "skunk": "🦨",
    "kangaroo": "🦘",
    "badger": "🦡",
    "paw prints": "🐾",
    "turkey": "🦃",
    "chicken": "🐔",
    "rooster": "🐓",
    "hatching chick": "🐣",
    "baby chick": "🐤",
    "front-facing baby chick": "🐥",
    "bird": "🐦",
    "penguin": "🐧",
    "️ dove": "🕊",
    "eagle": "🦅",
    "duck": "🦆",
    "swan": "🦢",
    "owl": "🦉",
    "dodo": "🦤",
    "feather": "🪶",
    "flamingo": "🦩",
    "peacock": "🦚",
    "parrot": "🦜",
    "frog": "🐸",
    "crocodile": "🐊",
    "turtle": "🐢",
    "lizard": "🦎",
    "snake": "🐍",
    "dragon face": "🐲",
    "dragon": "🐉",
    "sauropod": "🦕",
    "t-rex": "🦖",
    "spouting whale": "🐳",
    "whale": "🐋",
    "dolphin": "🐬",
    "seal": "🦭",
    "fish": "🐟",
    "tropical fish": "🐠",
    "blowfish": "🐡",
    "shark": "🦈",
    "octopus": "🐙",
    "spiral shell": "🐚",
    "snail": "🐌",
    "butterfly": "🦋",
    "bug": "🐛",
    "ant": "🐜",
    "honeybee": "🐝",
    "beetle": "🪲",
    "lady beetle": "🐞",
    "cricket": "🦗",
    "cockroach": "🪳",
    "️ spider": "🕷",
    "️ spider web": "🕸",
    "scorpion": "🦂",
    "mosquito": "🦟",
    "fly": "🪰",
    "worm": "🪱",
    "microbe": "🦠",
    "bouquet": "💐",
    "cherry blossom": "🌸",
    "white flower": "💮",
    "️ rosette": "🏵",
    "rose": "🌹",
    "wilted flower": "🥀",
    "hibiscus": "🌺",
    "sunflower": "🌻",
    "blossom": "🌼",
    "tulip": "🌷",
    "seedling": "🌱",
    "potted plant": "🪴",
    "evergreen tree": "🌲",
    "deciduous tree": "🌳",
    "palm tree": "🌴",
    "cactus": "🌵",
    "sheaf of rice": "🌾",
    "herb": "🌿",
    "shamrock": "☘️",
    "four leaf clover": "🍀",
    "maple leaf": "🍁",
    "fallen leaf": "🍂",
    "leaf fluttering in wind": "🍃",
    "mushroom": "🍄",
    "chestnut": "🌰",
    "crab": "🦀",
    "lobster": "🦞",
    "shrimp": "🦐",
    "squid": "🦑",
    "globe showing europe-africa": "🌍",
    "globe showing americas": "🌎",
    "globe showing asia-australia": "🌏",
    "globe with meridians": "🌐",
    "rock": "🪨",
    "new moon": "🌑",
    "waxing crescent moon": "🌒",
    "first quarter moon": "🌓",
    "waxing gibbous moon": "🌔",
    "full moon": "🌕",
    "waning gibbous moon": "🌖",
    "last quarter moon": "🌗",
    "waning crescent moon": "🌘",
    "crescent moon": "🌙",
    "new moon face": "🌚",
    "first quarter moon face": "🌛",
    "last quarter moon face": "🌜",
    "sun": "☀️",
    "full moon face": "🌝",
    "sun with face": "🌞",
    "star": "⭐",
    "glowing star": "🌟",
    "shooting star": "🌠",
    "cloud": "☁️",
    "sun behind cloud": "⛅",
    "cloud with lightning and rain": "⛈️",
    "️ sun behind small cloud": "🌤",
    "️ sun behind large cloud": "🌥",
    "️ sun behind rain cloud": "🌦",
    "️ cloud with rain": "🌧",
    "️ cloud with snow": "🌨",
    "️ cloud with lightning": "🌩",
    "️ tornado": "🌪",
    "️ fog": "🌫",
    "️ wind face": "🌬",
    "rainbow": "🌈",
    "umbrella": "☂️",
    "umbrella with rain drops": "☔",
    "high voltage": "⚡",
    "snowflake": "❄️",
    "snowman": "☃️",
    "snowman without snow": "⛄",
    "comet": "☄️",
    "fire": "🔥",
    "droplet": "💧",
    "water wave": "🌊",
    "christmas tree": "🎄",
    "sparkles": "✨",
    "tanabata tree": "🎋",
    "pine decoration": "🎍",
    "spoon": "🥄",
    "fork and knife": "🍴",
    "fork and knife with plate": "🍽️",
    "chopsticks": "🥢",
    "ice": "🧊",
    "mate": "🧉",
    "beverage box": "🧃",
    "bubble tea": "🧋",
    "cup with straw": "🥤",
    "tumbler glass": "🥃",
    "clinking glasses": "🥂",
    "clinking beer mugs": "🍻",
    "beer mug": "🍺",
    "tropical drink": "🍹",
    "cocktail glass": "🍸",
    "wine glass": "🍷",
    "bottle with popping cork": "🍾",
    "sake": "🍶",
    "teacup without handle": "🍵",
    "teapot": "🫖",
    "hot beverage": "☕",
    "glass of milk": "🥛",
    "baby bottle": "🍼",
    "honey pot": "🍯",
    "custard": "🍮",
    "lollipop": "🍭",
    "candy": "🍬",
    "chocolate bar": "🍫",
    "pie": "🥧",
    "cupcake": "🧁",
    "shortcake": "🍰",
    "birthday cake": "🎂",
    "cookie": "🍪",
    "doughnut": "🍩",
    "ice cream": "🍨",
    "shaved ice": "🍧",
    "soft ice cream": "🍦",
    "oyster": "🦪",
    "takeout box": "🥡",
    "fortune cookie": "🥠",
    "dumpling": "🥟",
    "dango": "🍡",
    "moon cake": "🥮",
    "fish cake with swirl": "🍥",
    "fried shrimp": "🍤",
    "sushi": "🍣",
    "oden": "🍢",
    "roasted sweet potato": "🍠",
    "spaghetti": "🍝",
    "steaming bowl": "🍜",
    "curry rice": "🍛",
    "cooked rice": "🍚",
    "rice ball": "🍙",
    "rice cracker": "🍘",
    "bento box": "🍱",
    "canned food": "🥫",
    "salt": "🧂",
    "butter": "🧈",
    "popcorn": "🍿",
    "green salad": "🥗",
    "bowl with spoon": "🥣",
    "fondue": "🫕",
    "pot of food": "🍲",
    "shallow pan of food": "🥘",
    "cooking": "🍳",
    "egg": "🥚",
    "falafel": "🧆",
    "stuffed flatbread": "🥙",
    "tamale": "🫔",
    "burrito": "🌯",
    "taco": "🌮",
    "sandwich": "🥪",
    "hot dog": "🌭",
    "pizza": "🍕",
    "french fries": "🍟",
    "hamburger": "🍔",
    "bacon": "🥓",
    "cut of meat": "🥩",
    "poultry leg": "🍗",
    "meat on bone": "🍖",
    "cheese wedge": "🧀",
    "waffle": "🧇",
    "pancakes": "🥞",
    "bagel": "🥯",
    "pretzel": "🥨",
    "flatbread": "🫓",
    "baguette bread": "🥖",
    "croissant": "🥐",
    "bread": "🍞",
    "chestnut": "🌰",
    "peanuts": "🥜",
    "mushroom": "🍄",
    "onion": "🧅",
    "garlic": "🧄",
    "broccoli": "🥦",
    "leafy green": "🥬",
    "cucumber": "🥒",
    "bell pepper": "🫑",
    "hot pepper": "🌶️",
    "ear of corn": "🌽",
    "carrot": "🥕",
    "potato": "🥔",
    "eggplant": "🍆",
    "avocado": "🥑",
    "coconut": "🥥",
    "olive": "🫒",
    "tomato": "🍅",
    "kiwi fruit": "🥝",
    "blueberries": "🫐",
    "strawberry": "🍓",
    "cherries": "🍒",
    "peach": "🍑",
    "pear": "🍐",
    "green apple": "🍏",
    "red apple": "🍎",
    "mango": "🥭",
    "pineapple": "🍍",
    "banana": "🍌",
    "lemon": "🍋",
    "tangerine": "🍊",
    "watermelon": "🍉",
    "melon": "🍈",
    "grapes": "🍇",
    "bow and arrow": "🏹",
    "clapper board": "🎬",
    "long drum": "🪘",
    "drum": "🥁",
    "violin": "🎻",
    "trumpet": "🎺",
    "musical keyboard": "🎹",
    "guitar": "🎸",
    "accordion": "🪗",
    "saxophone": "🎷",
    "headphone": "🎧",
    "microphone": "🎤",
    "musical score": "🎼",
    "yarn": "🧶",
    "thread": "🧵",
    "artist palette": "🎨",
    "performing arts": "🎭",
    "chess pawn": "♟️",
    "puzzle piece": "🧩",
    "game die": "🎲",
    "slot machine": "🎰",
    "video game": "🎮",
    "pool 8 ball": "🎱",
    "bullseye": "🎯",
    "curling stone": "🥌",
    "sled": "🛷",
    "skis": "🎿",
    "running shirt": "🎽",
    "fishing pole": "🎣",
    "ice skate": "⛸️",
    "flag in hole": "⛳",
    "goal net": "🥅",
    "martial arts uniform": "🥋",
    "boxing glove": "🥊",
    "badminton": "🏸",
    "ping pong": "🏓",
    "lacrosse": "🥍",
    "ice hockey": "🏒",
    "field hockey": "🏑",
    "cricket game": "🏏",
    "bowling": "🎳",
    "flying disc": "🥏",
    "tennis": "🎾",
    "rugby football": "🏉",
    "american football": "🏈",
    "volleyball": "🏐",
    "basketball": "🏀",
    "softball": "🥎",
    "baseball": "⚾",
    "soccer ball": "⚽",
    "3rd place medal": "🥉",
    "2nd place medal": "🥈",
    "1st place medal": "🥇",
    "sports medal": "🏅",
    "trophy": "🏆",
    "military medal": "🎖️",
    "ticket": "🎫",
    "admission tickets": "🎟️",
    "reminder ribbon": "🎗️",
    "canoe": "🛶",
    "roller skate": "🛼",
    "skateboard": "🛹",
    "circus tent": "🎪",
    "woman in lotus position": "🧘‍♀️",
    "man in lotus position": "🧘‍♂️",
    "person in lotus position": "🧘",
    "woman juggling": "🤹‍♀️",
    "man juggling": "🤹‍♂️",
    "person juggling": "🤹",
    "woman playing handball": "🤾‍♀️",
    "man playing handball": "🤾‍♂️",
    "person playing handball": "🤾",
    "woman playing water polo": "🤽‍♀️",
    "man playing water polo": "🤽‍♂️",
    "person playing water polo": "🤽",
    "women wrestling": "🤼‍♀️",
    "men wrestling": "🤼‍♂️",
    "people wrestling": "🤼",
    "woman cartwheeling": "🤸‍♀️",
    "man cartwheeling": "🤸‍♂️",
    "person cartwheeling": "🤸",
    "woman mountain biking": "🚵‍♀️",
    "man mountain biking": "🚵‍♂️",
    "person mountain biking": "🚵",
    "woman biking": "🚴‍♀️",
    "man biking": "🚴‍♂️",
    "person biking": "🚴",
    "woman lifting weights": "🏋️‍♀️",
    "man lifting weights": "🏋️‍♂️",
    "person lifting weights": "🏋️",
    "woman bouncing ball": "⛹️‍♀️",
    "man bouncing ball": "⛹️‍♂️",
    "person bouncing ball": "⛹️",
    "woman swimming": "🏊‍♀️",
    "man swimming": "🏊‍♂️",
    "person swimming": "🏊",
    "woman rowing boat": "🚣‍♀️",
    "man rowing boat": "🚣‍♂️",
    "person rowing boat": "🚣",
    "woman surfing": "🏄‍♀️",
    "man surfing": "🏄‍♂️",
    "person surfing": "🏄",
    "woman golfing": "🏌️‍♀️",
    "man golfing": "🏌️‍♂️",
    "person golfing": "🏌️",
    "snowboarder": "🏂",
    "skier": "⛷️",
    "horse racing": "🏇",
    "person fencing": "🤺",
    "woman climbing": "🧗‍♀️",
    "man climbing": "🧗‍♂️",
    "person climbing": "🧗",
    "person in suit levitating": "🕴️",
    "left luggage": "🛅",
    "baggage claim": "🛄",
    "customs": "🛃",
    "passport control": "🛂",
    "moai": "🗿",
    "pound banknote": "💷",
    "euro banknote": "💶",
    "dollar banknote": "💵",
    "yen banknote": "💴",
    "moon viewing ceremony": "🎑",
    "sparkler": "🎇",
    "fireworks": "🎆",
    "umbrella on ground": "⛱️",
    "milky way": "🌌",
    "shooting star": "🌠",
    "ringed planet": "🪐",
    "flying saucer": "🛸",
    "rocket": "🚀",
    "satellite": "🛰️",
    "aerial tramway": "🚡",
    "mountain cableway": "🚠",
    "suspension railway": "🚟",
    "helicopter": "🚁",
    "seat": "💺",
    "parachute": "🪂",
    "airplane arrival": "🛬",
    "airplane departure": "🛫",
    "small airplane": "🛩️",
    "airplane": "✈️",
    "ship": "🚢",
    "motor boat": "🛥️",
    "ferry": "⛴️",
    "passenger ship": "🛳️",
    "speedboat": "🚤",
    "sailboat": "⛵",
    "anchor": "⚓",
    "construction": "🚧",
    "vertical traffic light": "🚦",
    "horizontal traffic light": "🚥",
    "police car light": "🚨",
    "fuel pump": "⛽",
    "railway track": "🛤️",
    "motorway": "🛣️",
    "bus stop": "🚏",
    "kick scooter": "🛴",
    "bicycle": "🚲",
    "auto rickshaw": "🛺",
    "motor scooter": "🛵",
    "motorcycle": "🏍️",
    "racing car": "🏎️",
    "tractor": "🚜",
    "articulated lorry": "🚛",
    "delivery truck": "🚚",
    "pickup truck": "🛻",
    "sport utility vehicle": "🚙",
    "oncoming automobile": "🚘",
    "automobile": "🚗",
    "oncoming taxi": "🚖",
    "taxi": "🚕",
    "oncoming police car": "🚔",
    "police car": "🚓",
    "fire engine": "🚒",
    "ambulance": "🚑",
    "minibus": "🚐",
    "trolleybus": "🚎",
    "oncoming bus": "🚍",
    "bus": "🚌",
    "tram car": "🚋",
    "mountain railway": "🚞",
    "monorail": "🚝",
    "tram": "🚊",
    "station": "🚉",
    "light rail": "🚈",
    "metro": "🚇",
    "train": "🚆",
    "bullet train": "🚅",
    "high-speed train": "🚄",
    "railway car": "🚃",
    "locomotive": "🚂",
    "roller coaster": "🎢",
    "ferris wheel": "🎡",
    "carousel horse": "🎠",
    "bridge at night": "🌉",
    "sunset": "🌇",
    "cityscape at dusk": "🌆",
    "sunrise": "🌅",
    "sunrise over mountains": "🌄",
    "cityscape": "🏙️",
    "night with stars": "🌃",
    "foggy": "🌁",
    "tent": "⛺",
    "fountain": "⛲",
    "kaaba": "🕋",
    "shinto shrine": "⛩️",
    "synagogue": "🕍",
    "hindu temple": "🛕",
    "mosque": "🕌",
    "church": "⛪",
    "statue of liberty": "🗽",
    "tokyo tower": "🗼",
    "wedding": "💒",
    "castle": "🏰",
    "japanese castle": "🏯",
    "factory": "🏭",
    "department store": "🏬",
    "school": "🏫",
    "convenience store": "🏪",
    "love hotel": "🏩",
    "hotel": "🏨",
    "bank": "🏦",
    "hospital": "🏥",
    "post office": "🏤",
    "japanese post office": "🏣",
    "office building": "🏢",
    "house with garden": "🏡",
    "house": "🏠",
    "derelict house": "🏚️",
    "houses": "🏘️",
    "hut": "🛖",
    "building construction": "🏗️",
    "classical building": "🏛️",
    "stadium": "🏟️",
    "national park": "🏞️",
    "desert island": "🏝️",
    "desert": "🏜️",
    "beach with umbrella": "🏖️",
    "camping": "🏕️",
    "mount fuji": "🗻",
    "volcano": "🌋",
    "mountain": "⛰️",
    "snow-capped mountain": "🏔️",
    "map of japan": "🗾",
    "person rowing boat": "🚣",
    "potable water": "🚰",
    "placard": "🪧",
    "moai": "🗿",
    "funeral urn": "⚱️",
    "headstone": "🪦",
    "coffin": "⚰️",
    "cigarette": "🚬",
    "shopping cart": "🛒",
    "fire extinguisher": "🧯",
    "sponge": "🧽",
    "toothbrush": "🪥",
    "soap": "🧼",
    "bucket": "🪣",
    "roll of paper": "🧻",
    "basket": "🧺",
    "broom": "🧹",
    "safety pin": "🧷",
    "lotion bottle": "🧴",
    "razor": "🪒",
    "mouse trap": "🪤",
    "bathtub": "🛁",
    "shower": "🚿",
    "plunger": "🪠",
    "toilet": "🚽",
    "chair": "🪑",
    "couch and lamp": "🛋️",
    "bed": "🛏️",
    "window": "🪟",
    "mirror": "🪞",
    "door": "🚪",
    "stethoscope": "🩺",
    "adhesive bandage": "🩹",
    "pill": "💊",
    "drop of blood": "🩸",
    "syringe": "💉",
    "satellite antenna": "📡",
    "telescope": "🔭",
    "microscope": "🔬",
    "dna": "🧬",
    "petri dish": "🧫",
    "test tube": "🧪",
    "alembic": "⚗️",
    "ladder": "🪜",
    "magnet": "🧲",
    "toolbox": "🧰",
    "hook": "🪝",
    "chains": "⛓️",
    "link": "🔗",
    "white cane": "🦯",
    "balance scale": "⚖️",
    "clamp": "🗜️",
    "gear": "⚙️",
    "nut and bolt": "🔩",
    "screwdriver": "🪛",
    "wrench": "🔧",
    "carpentry saw": "🪚",
    "shield": "🛡️",
    "boomerang": "🪃",
    "water pistol": "🔫",
    "crossed swords": "⚔️",
    "dagger": "🗡️",
    "hammer and wrench": "🛠️",
    "hammer and pick": "⚒️",
    "pick": "⛏️",
    "axe": "🪓",
    "hammer": "🔨",
    "old key": "🗝️",
    "key": "🔑",
    "locked with key": "🔐",
    "locked with pen": "🔏",
    "unlocked": "🔓",
    "locked": "🔒",
    "wastebasket": "🗑️",
    "file cabinet": "🗄️",
    "card file box": "🗃️",
    "scissors": "✂️",
    "triangular ruler": "📐",
    "straight ruler": "📏",
    "linked paperclips": "🖇️",
    "paperclip": "📎",
    "round pushpin": "📍",
    "pushpin": "📌",
    "clipboard": "📋",
    "bar chart": "📊",
    "chart decreasing": "📉",
    "chart increasing": "📈",
    "card index": "📇",
    "spiral calendar": "🗓️",
    "spiral notepad": "🗒️",
    "tear-off calendar": "📆",
    "calendar": "📅",
    "card index dividers": "🗂️",
    "open file folder": "📂",
    "file folder": "📁",
    "memo": "📝",
    "crayon": "🖍️",
    "paintbrush": "🖌️",
    "pen": "🖊️",
    "fountain pen": "🖋️",
    "black nib": "✒️",
    "pencil": "✏️",
    "ballot box with ballot": "🗳️",
    "postbox": "📮",
    "open mailbox with lowered flag": "📭",
    "open mailbox with raised flag": "📬",
    "closed mailbox with lowered flag": "📪",
    "closed mailbox with raised flag": "📫",
    "package": "📦",
    "inbox tray": "📥",
    "outbox tray": "📤",
    "envelope with arrow": "📩",
    "incoming envelope": "📨",
    "e-mail": "📧",
    "envelope": "✉️",
    "receipt": "🧾",
    "credit card": "💳",
    "money with wings": "💸",
    "pound banknote": "💷",
    "euro banknote": "💶",
    "dollar banknote": "💵",
    "yen banknote": "💴",
    "coin": "🪙",
    "money bag": "💰",
    "label": "🏷️",
    "bookmark": "🔖",
    "bookmark tabs": "📑",
    "rolled-up newspaper": "🗞️",
    "newspaper": "📰",
    "page facing up": "📄",
    "scroll": "📜",
    "page with curl": "📃",
    "ledger": "📒",
    "notebook": "📓",
    "books": "📚",
    "orange book": "📙",
    "blue book": "📘",
    "green book": "📗",
    "open book": "📖",
    "closed book": "📕",
    "notebook with decorative cover": "📔",
    "diya lamp": "🪔",
    "red paper lantern": "🏮",
    "flashlight": "🔦",
    "light bulb": "💡",
    "candle": "🕯️",
    "magnifying glass tilted right": "🔎",
    "magnifying glass tilted left": "🔍",
    "videocassette": "📼",
    "video camera": "📹",
    "camera with flash": "📸",
    "camera": "📷",
    "television": "📺",
    "film projector": "📽️",
    "film frames": "🎞️",
    "movie camera": "🎥",
    "abacus": "🧮",
    "dvd": "📀",
    "optical disk": "💿",
    "floppy disk": "💾",
    "computer disk": "💽",
    "trackball": "🖲️",
    "computer mouse": "🖱️",
    "keyboard": "⌨️",
    "printer": "🖨️",
    "desktop computer": "🖥️",
    "laptop": "💻",
    "electric plug": "🔌",
    "battery": "🔋",
    "fax machine": "📠",
    "pager": "📟",
    "telephone receiver": "📞",
    "telephone": "☎️",
    "mobile phone with arrow": "📲",
    "mobile phone": "📱",
    "banjo": "🪕",
    "radio": "📻",
    "control knobs": "🎛️",
    "level slider": "🎚️",
    "studio microphone": "🎙️",
    "postal horn": "📯",
    "gem stone": "💎",
    "prayer beads": "📿",
    "shopping bags": "🛍️",
    "knot": "🪢",
    "yarn": "🧶",
    "sewing needle": "🪡",
    "thread": "🧵",
    "framed picture": "🖼️",
    "nesting dolls": "🪆",
    "piñata": "🪅",
    "teddy bear": "🧸",
    "joystick": "🕹️",
    "nazar amulet": "🧿",
    "magic wand": "🪄",
    "crystal ball": "🔮",
    "kite": "🪁",
    "yo-yo": "🪀",
    "diving mask": "🤿",
    "wrapped gift": "🎁",
    "ribbon": "🎀",
    "red envelope": "🧧",
    "wind chime": "🎐",
    "carp streamer": "🎏",
    "japanese dolls": "🎎",
    "confetti ball": "🎊",
    "party popper": "🎉",
    "balloon": "🎈",
    "firecracker": "🧨",
    "umbrella on ground": "⛱️",
    "thermometer": "🌡️",
    "mantelpiece clock": "🕰️",
    "timer clock": "⏲️",
    "stopwatch": "⏱️",
    "alarm clock": "⏰",
    "watch": "⌚",
    "hourglass not done": "⏳",
    "hourglass done": "⌛",
    "luggage": "🧳",
    "bellhop bell": "🛎️",
    "oil drum": "🛢️",
    "motorized wheelchair": "🦼",
    "manual wheelchair": "🦽",
    "barber pole": "💈",
    "brick": "🧱",
    "compass": "🧭",
    "world map": "🗺️",
    "amphora": "🏺",
    "kitchen knife": "🔪",
    "person in bed": "🛌",
    "person taking bath": "🛀",
    "bomb": "💣",
    "hole": "🕳️",
    "love letter": "💌",
    "black square button": "🔲",
    "white square button": "🔳",
    "radio button": "🔘",
    "diamond with a dot": "💠",
    "red triangle pointed down": "🔻",
    "red triangle pointed up": "🔺",
    "small blue diamond": "🔹",
    "small orange diamond": "🔸",
    "large blue diamond": "🔷",
    "large orange diamond": "🔶",
    "white small square": "▫️",
    "black small square": "▪️",
    "white medium-small square": "◽",
    "black medium-small square": "◾",
    "white medium square": "◻️",
    "black medium square": "◼️",
    "white large square": "⬜",
    "black large square": "⬛",
    "brown square": "🟫",
    "purple square": "🟪",
    "blue square": "🟦",
    "green square": "🟩",
    "yellow square": "🟨",
    "orange square": "🟧",
    "red square": "🟥",
    "white circle": "⚪",
    "black circle": "⚫",
    "brown circle": "🟤",
    "purple circle": "🟣",
    "blue circle": "🔵",
    "green circle": "🟢",
    "yellow circle": "🟡",
    "orange circle": "🟠",
    "red circle": "🔴",
    "japanese “no vacancy” button": "🈵",
    "japanese “open for business” button": "🈺",
    "japanese “secret” button": "㊙️",
    "japanese “congratulations” button": "㊗️",
    "japanese “vacancy” button": "🈳",
    "japanese “passing grade” button": "🈴",
    "japanese “application” button": "🈸",
    "japanese “acceptable” button": "🉑",
    "japanese “prohibited” button": "🈲",
    "japanese “free of charge” button": "🈚",
    "japanese “discount” button": "🈹",
    "japanese “bargain” button": "🉐",
    "japanese “reserved” button": "🈯",
    "japanese “not free of charge” button": "🈶",
    "japanese “monthly amount” button": "🈷️",
    "japanese “service charge” button": "🈂️",
    "japanese “here” button": "🈁",
    "vs button": "🆚",
    "up! button": "🆙",
    "sos button": "🆘",
    "p button": "🅿️",
    "ok button": "🆗",
    "o button (blood type)": "🅾️",
    "ng button": "🆖",
    "new button": "🆕",
    "circled m": "Ⓜ️",
    "id button": "🆔",
    "information": "ℹ️",
    "free button": "🆓",
    "cool button": "🆒",
    "cl button": "🆑",
    "b button (blood type)": "🅱️",
    "ab button (blood type)": "🆎",
    "a button (blood type)": "🅰️",
    "input latin letters": "🔤",
    "input symbols": "🔣",
    "input numbers": "🔢",
    "input latin lowercase": "🔡",
    "input latin uppercase": "🔠",
    "keycap: 10": "🔟",
    "keycap digit nine": "9️⃣",
    "keycap digit eight": "8️⃣",
    "keycap digit seven": "7️⃣",
    "keycap digit six": "6️⃣",
    "keycap digit five": "5️⃣",
    "keycap digit four": "4️⃣",
    "keycap digit three": "3️⃣",
    "keycap digit two": "2️⃣",
    "keycap digit one": "1️⃣",
    "keycap digit zero": "0️⃣",
    "keycap asterisk": "*️⃣",
    "keycap number sign": "#️⃣",
    "trade mark": "™️",
    "registered": "®️",
    "copyright": "©️",
    "sparkle": "❇️",
    "eight-pointed star": "✴️",
    "eight-spoked asterisk": "✳️",
    "part alternation mark": "〽️",
    "double curly loop": "➿",
    "curly loop": "➰",
    "cross mark button": "❎",
    "cross mark": "❌",
    "check mark": "✔️",
    "check box with check": "☑️",
    "check mark button": "✅",
    "hollow red circle": "⭕",
    "japanese symbol for beginner": "🔰",
    "name badge": "📛",
    "trident emblem": "🔱",
    "fleur-de-lis": "⚜️",
    "recycling symbol": "♻️",
    "medical symbol": "⚕️",
    "heavy dollar sign": "💲",
    "currency exchange": "💱",
    "wavy dash": "〰️",
    "red exclamation mark": "❗",
    "white exclamation mark": "❕",
    "white question mark": "❔",
    "red question mark": "❓",
    "exclamation question mark": "⁉️",
    "double exclamation mark": "‼️",
    "infinity": "♾️",
    "divide": "➗",
    "minus": "➖",
    "plus": "➕",
    "multiply": "✖️",
    "male sign": "♂️",
    "female sign": "♀️",
    "mobile phone off": "📴",
    "vibration mode": "📳",
    "antenna bars": "📶",
    "bright button": "🔆",
    "dim button": "🔅",
    "cinema": "🎦",
    "eject button": "⏏️",
    "record button": "⏺️",
    "stop button": "⏹️",
    "pause button": "⏸️",
    "fast down button": "⏬",
    "downwards button": "🔽",
    "fast up button": "⏫",
    "upwards button": "🔼",
    "last track button": "⏮️",
    "fast reverse button": "⏪",
    "reverse button": "◀️",
    "play or pause button": "⏯️",
    "next track button": "⏭️",
    "fast-forward button": "⏩",
    "play button": "▶️",
    "repeat single button": "🔂",
    "repeat button": "🔁",
    "shuffle tracks button": "🔀",
    "ophiuchus": "⛎",
    "pisces": "♓",
    "aquarius": "♒",
    "capricorn": "♑",
    "sagittarius": "♐",
    "scorpio": "♏",
    "libra": "♎",
    "virgo": "♍",
    "leo": "♌",
    "cancer": "♋",
    "gemini": "♊",
    "taurus": "♉",
    "aries": "♈",
    "dotted six-pointed star": "🔯",
    "menorah": "🕎",
    "peace symbol": "☮️",
    "star and crescent": "☪️",
    "orthodox cross": "☦️",
    "latin cross": "✝️",
    "yin yang": "☯️",
    "wheel of dharma": "☸️",
    "star of david": "✡️",
    "om": "🕉️",
    "atom symbol": "⚛️",
    "place of worship": "🛐",
    "top arrow": "🔝",
    "soon arrow": "🔜",
    "on! arrow": "🔛",
    "end arrow": "🔚",
    "back arrow": "🔙",
    "counterclockwise arrows button": "🔄",
    "clockwise vertical arrows": "🔃",
    "right arrow curving down": "⤵️",
    "right arrow curving up": "⤴️",
    "left arrow curving right": "↪️",
    "right arrow curving left": "↩️",
    "left-right arrow": "↔️",
    "up-down arrow": "↕️",
    "up-left arrow": "↖️",
    "left arrow": "⬅️",
    "down-left arrow": "↙️",
    "down arrow": "⬇️",
    "down-right arrow": "↘️",
    "right arrow": "➡️",
    "up-right arrow": "↗️",
    "up arrow": "⬆️",
    "biohazard": "☣️",
    "radioactive": "☢️",
    "no one under eighteen": "🔞",
    "no mobile phones": "📵",
    "no pedestrians": "🚷",
    "non-potable water": "🚱",
    "no littering": "🚯",
    "no smoking": "🚭",
    "no bicycles": "🚳",
    "prohibited": "🚫",
    "no entry": "⛔",
    "children crossing": "🚸",
    "warning": "⚠️",
    "water closet": "🚾",
    "baby symbol": "🚼",
    "restroom": "🚻",
    "women’s room": "🚺",
    "men’s room": "🚹",
    "wheelchair symbol": "♿",
    "potable water": "🚰",
    "litter in bin sign": "🚮",
    "atm sign": "🏧",
    "elevator": "🛗",
    "chart increasing with yen": "💹",
    "musical notes": "🎶",
    "musical note": "🎵",
    "bell with slash": "🔕",
    "bell": "🔔",
    "postal horn": "📯",
    "megaphone": "📣",
    "loudspeaker": "📢",
    "speaker high volume": "🔊",
    "speaker medium volume": "🔉",
    "speaker low volume": "🔈",
    "muted speaker": "🔇",
    "flower playing cards": "🎴",
    "mahjong red dragon": "🀄",
    "joker": "🃏",
    "club suit": "♣️",
    "diamond suit": "♦️",
    "heart suit": "♥️",
    "spade suit": "♠️",
    "cyclone": "🌀",
    "eleven-thirty": "🕦",
    "eleven o’clock": "🕚",
    "ten-thirty": "🕥",
    "ten o’clock": "🕙",
    "nine-thirty": "🕤",
    "nine o’clock": "🕘",
    "eight-thirty": "🕣",
    "eight o’clock": "🕗",
    "seven-thirty": "🕢",
    "seven o’clock": "🕖",
    "six-thirty": "🕡",
    "six o’clock": "🕕",
    "five-thirty": "🕠",
    "five o’clock": "🕔",
    "four-thirty": "🕟",
    "four o’clock": "🕓",
    "three-thirty": "🕞",
    "three o’clock": "🕒",
    "two-thirty": "🕝",
    "two o’clock": "🕑",
    "one-thirty": "🕜",
    "one o’clock": "🕐",
    "twelve-thirty": "🕧",
    "twelve o’clock": "🕛",
    "stop sign": "🛑",
    "barber pole": "💈",
    "hot springs": "♨️",
    "white flower": "💮",
    "zzz": "💤",
    "thought balloon": "💭",
    "right anger bubble": "🗯️",
    "left speech bubble": "🗨️",
    "eye in speech bubble": "👁️‍🗨️",
    "speech balloon": "💬",
    "anger symbol": "💢",
    "hundred points": "💯",
    "white heart": "🤍",
    "black heart": "🖤",
    "brown heart": "🤎",
    "purple heart": "💜",
    "blue heart": "💙",
    "green heart": "💚",
    "yellow heart": "💛",
    "orange heart": "🧡",
    "red heart": "❤️",
    "mending heart": "❤️‍🩹",
    "heart on fire": "❤️‍🔥",
    "broken heart": "💔",
    "heart exclamation": "❣️",
    "heart decoration": "💟",
    "two hearts": "💕",
    "revolving hearts": "💞",
    "beating heart": "💓",
    "growing heart": "💗",
    "sparkling heart": "💖",
    "heart with ribbon": "💝",
    "heart with arrow": "💘",
    "refugee nation flag": "🏳‍🟧‍⬛‍🟧",
    "flag for texas (us-tx)": "🏴󠁵󠁳󠁴󠁸󠁿",
    "flag: wales": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
    "flag: scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    "flag: england": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "flag: zimbabwe": "🇿🇼",
    "flag: zambia": "🇿🇲",
    "flag: south africa": "🇿🇦",
    "flag: mayotte": "🇾🇹",
    "flag: yemen": "🇾🇪",
    "flag: kosovo": "🇽🇰",
    "flag: samoa": "🇼🇸",
    "flag: wallis & futuna": "🇼🇫",
    "flag: vanuatu": "🇻🇺",
    "flag: vietnam": "🇻🇳",
    "flag: u.s. virgin islands": "🇻🇮",
    "flag: british virgin islands": "🇻🇬",
    "flag: venezuela": "🇻🇪",
    "flag: st. vincent & grenadines": "🇻🇨",
    "flag: vatican city": "🇻🇦",
    "flag: uzbekistan": "🇺🇿",
    "flag: uruguay": "🇺🇾",
    "flag: united states": "🇺🇸",
    "flag: united nations": "🇺🇳",
    "flag: u.s. outlying islands": "🇺🇲",
    "flag: uganda": "🇺🇬",
    "flag: ukraine": "🇺🇦",
    "flag: tanzania": "🇹🇿",
    "flag: taiwan": "🇹🇼",
    "flag: tuvalu": "🇹🇻",
    "flag: trinidad & tobago": "🇹🇹",
    "flag: turkey": "🇹🇷",
    "flag: tonga": "🇹🇴",
    "flag: tunisia": "🇹🇳",
    "flag: turkmenistan": "🇹🇲",
    "flag: timor-leste": "🇹🇱",
    "flag: tokelau": "🇹🇰",
    "flag: tajikistan": "🇹🇯",
    "flag: thailand": "🇹🇭",
    "flag: togo": "🇹🇬",
    "flag: french southern territories": "🇹🇫",
    "flag: chad": "🇹🇩",
    "flag: turks & caicos islands": "🇹🇨",
    "flag: tristan da cunha": "🇹🇦",
    "flag: eswatini": "🇸🇿",
    "flag: syria": "🇸🇾",
    "flag: sint maarten": "🇸🇽",
    "flag: el salvador": "🇸🇻",
    "flag: são tomé & príncipe": "🇸🇹",
    "flag: south sudan": "🇸🇸",
    "flag: suriname": "🇸🇷",
    "flag: somalia": "🇸🇴",
    "flag: senegal": "🇸🇳",
    "flag: san marino": "🇸🇲",
    "flag: sierra leone": "🇸🇱",
    "flag: slovakia": "🇸🇰",
    "flag: svalbard & jan mayen": "🇸🇯",
    "flag: slovenia": "🇸🇮",
    "flag: st. helena": "🇸🇭",
    "flag: singapore": "🇸🇬",
    "flag: sweden": "🇸🇪",
    "flag: sudan": "🇸🇩",
    "flag: seychelles": "🇸🇨",
    "flag: solomon islands": "🇸🇧",
    "flag: saudi arabia": "🇸🇦",
    "flag: rwanda": "🇷🇼",
    "flag: russia": "🇷🇺",
    "flag: serbia": "🇷🇸",
    "flag: romania": "🇷🇴",
    "flag: réunion": "🇷🇪",
    "flag: qatar": "🇶🇦",
    "flag: paraguay": "🇵🇾",
    "flag: palau": "🇵🇼",
    "flag: portugal": "🇵🇹",
    "flag: palestinian territories": "🇵🇸",
    "flag: puerto rico": "🇵🇷",
    "flag: pitcairn islands": "🇵🇳",
    "flag: st. pierre & miquelon": "🇵🇲",
    "flag: poland": "🇵🇱",
    "flag: pakistan": "🇵🇰",
    "flag: philippines": "🇵🇭",
    "flag: papua new guinea": "🇵🇬",
    "flag: french polynesia": "🇵🇫",
    "flag: peru": "🇵🇪",
    "flag: panama": "🇵🇦",
    "flag: oman": "🇴🇲",
    "flag: new zealand": "🇳🇿",
    "flag: niue": "🇳🇺",
    "flag: nauru": "🇳🇷",
    "flag: nepal": "🇳🇵",
    "flag: norway": "🇳🇴",
    "flag: netherlands": "🇳🇱",
    "flag: nicaragua": "🇳🇮",
    "flag: nigeria": "🇳🇬",
    "flag: norfolk island": "🇳🇫",
    "flag: niger": "🇳🇪",
    "flag: new caledonia": "🇳🇨",
    "flag: namibia": "🇳🇦",
    "flag: mozambique": "🇲🇿",
    "flag: malaysia": "🇲🇾",
    "flag: mexico": "🇲🇽",
    "flag: malawi": "🇲🇼",
    "flag: maldives": "🇲🇻",
    "flag: mauritius": "🇲🇺",
    "flag: malta": "🇲🇹",
    "flag: montserrat": "🇲🇸",
    "flag: mauritania": "🇲🇷",
    "flag: martinique": "🇲🇶",
    "flag: northern mariana islands": "🇲🇵",
    "flag: macao sar china": "🇲🇴",
    "flag: mongolia": "🇲🇳",
    "flag: myanmar (burma)": "🇲🇲",
    "flag: mali": "🇲🇱",
    "flag: north macedonia": "🇲🇰",
    "flag: marshall islands": "🇲🇭",
    "flag: madagascar": "🇲🇬",
    "flag: st. martin": "🇲🇫",
    "flag: montenegro": "🇲🇪",
    "flag: moldova": "🇲🇩",
    "flag: monaco": "🇲🇨",
    "flag: morocco": "🇲🇦",
    "flag: libya": "🇱🇾",
    "flag: latvia": "🇱🇻",
    "flag: luxembourg": "🇱🇺",
    "flag: lithuania": "🇱🇹",
    "flag: lesotho": "🇱🇸",
    "flag: liberia": "🇱🇷",
    "flag: sri lanka": "🇱🇰",
    "flag: liechtenstein": "🇱🇮",
    "flag: st. lucia": "🇱🇨",
    "flag: lebanon": "🇱🇧",
    "flag: laos": "🇱🇦",
    "flag: kazakhstan": "🇰🇿",
    "flag: cayman islands": "🇰🇾",
    "flag: kuwait": "🇰🇼",
    "flag: south korea": "🇰🇷",
    "flag: north korea": "🇰🇵",
    "flag: st. kitts & nevis": "🇰🇳",
    "flag: comoros": "🇰🇲",
    "flag: kiribati": "🇰🇮",
    "flag: cambodia": "🇰🇭",
    "flag: kyrgyzstan": "🇰🇬",
    "flag: kenya": "🇰🇪",
    "flag: japan": "🇯🇵",
    "flag: jordan": "🇯🇴",
    "flag: jamaica": "🇯🇲",
    "flag: jersey": "🇯🇪",
    "flag: italy": "🇮🇹",
    "flag: iceland": "🇮🇸",
    "flag: iran": "🇮🇷",
    "flag: iraq": "🇮🇶",
    "flag: british indian ocean territory": "🇮🇴",
    "flag: india": "🇮🇳",
    "flag: isle of man": "🇮🇲",
    "flag: israel": "🇮🇱",
    "flag: ireland": "🇮🇪",
    "flag: indonesia": "🇮🇩",
    "flag: canary islands": "🇮🇨",
    "flag: hungary": "🇭🇺",
    "flag: haiti": "🇭🇹",
    "flag: croatia": "🇭🇷",
    "flag: honduras": "🇭🇳",
    "flag: heard & mcdonald islands": "🇭🇲",
    "flag: hong kong sar china": "🇭🇰",
    "flag: guyana": "🇬🇾",
    "flag: guinea-bissau": "🇬🇼",
    "flag: guam": "🇬🇺",
    "flag: guatemala": "🇬🇹",
    "flag: south georgia & south sandwich islands": "🇬🇸",
    "flag: greece": "🇬🇷",
    "flag: equatorial guinea": "🇬🇶",
    "flag: guadeloupe": "🇬🇵",
    "flag: guinea": "🇬🇳",
    "flag: gambia": "🇬🇲",
    "flag: greenland": "🇬🇱",
    "flag: gibraltar": "🇬🇮",
    "flag: ghana": "🇬🇭",
    "flag: guernsey": "🇬🇬",
    "flag: french guiana": "🇬🇫",
    "flag: georgia": "🇬🇪",
    "flag: grenada": "🇬🇩",
    "flag: united kingdom": "🇬🇧",
    "flag: gabon": "🇬🇦",
    "flag: france": "🇫🇷",
    "flag: faroe islands": "🇫🇴",
    "flag: micronesia": "🇫🇲",
    "flag: falkland islands": "🇫🇰",
    "flag: fiji": "🇫🇯",
    "flag: finland": "🇫🇮",
    "flag: european union": "🇪🇺",
    "flag: ethiopia": "🇪🇹",
    "flag: spain": "🇪🇸",
    "flag: eritrea": "🇪🇷",
    "flag: western sahara": "🇪🇭",
    "flag: egypt": "🇪🇬",
    "flag: estonia": "🇪🇪",
    "flag: ecuador": "🇪🇨",
    "flag: ceuta & melilla": "🇪🇦",
    "flag: algeria": "🇩🇿",
    "flag: dominican republic": "🇩🇴",
    "flag: dominica": "🇩🇲",
    "flag: denmark": "🇩🇰",
    "flag: djibouti": "🇩🇯",
    "flag: diego garcia": "🇩🇬",
    "flag: germany": "🇩🇪",
    "flag: czechia": "🇨🇿",
    "flag: cyprus": "🇨🇾",
    "flag: christmas island": "🇨🇽",
    "flag: curaçao": "🇨🇼",
    "flag: cape verde": "🇨🇻",
    "flag: cuba": "🇨🇺",
    "flag: costa rica": "🇨🇷",
    "flag: clipperton island": "🇨🇵",
    "flag: colombia": "🇨🇴",
    "flag: china": "🇨🇳",
    "flag: cameroon": "🇨🇲",
    "flag: chile": "🇨🇱",
    "flag: cook islands": "🇨🇰",
    "flag: côte d’ivoire": "🇨🇮",
    "flag: switzerland": "🇨🇭",
    "flag: congo - brazzaville": "🇨🇬",
    "flag: central african republic": "🇨🇫",
    "flag: congo - kinshasa": "🇨🇩",
    "flag: cocos (keeling) islands": "🇨🇨",
    "flag: canada": "🇨🇦",
    "flag: belize": "🇧🇿",
    "flag: belarus": "🇧🇾",
    "flag: botswana": "🇧🇼",
    "flag: bouvet island": "🇧🇻",
    "flag: bhutan": "🇧🇹",
    "flag: bahamas": "🇧🇸",
    "flag: brazil": "🇧🇷",
    "flag: caribbean netherlands": "🇧🇶",
    "flag: bolivia": "🇧🇴",
    "flag: brunei": "🇧🇳",
    "flag: bermuda": "🇧🇲",
    "flag: st. barthélemy": "🇧🇱",
    "flag: benin": "🇧🇯",
    "flag: burundi": "🇧🇮",
    "flag: bahrain": "🇧🇭",
    "flag: bulgaria": "🇧🇬",
    "flag: burkina faso": "🇧🇫",
    "flag: belgium": "🇧🇪",
    "flag: bangladesh": "🇧🇩",
    "flag: barbados": "🇧🇧",
    "flag: bosnia & herzegovina": "🇧🇦",
    "flag: azerbaijan": "🇦🇿",
    "flag: åland islands": "🇦🇽",
    "flag: aruba": "🇦🇼",
    "flag: australia": "🇦🇺",
    "flag: austria": "🇦🇹",
    "flag: american samoa": "🇦🇸",
    "flag: argentina": "🇦🇷",
    "flag: antarctica": "🇦🇶",
    "flag: angola": "🇦🇴",
    "flag: armenia": "🇦🇲",
    "flag: albania": "🇦🇱",
    "flag: anguilla": "🇦🇮",
    "flag: antigua & barbuda": "🇦🇬",
    "flag: afghanistan": "🇦🇫",
    "flag: united arab emirates": "🇦🇪",
    "flag: andorra": "🇦🇩",
    "flag: ascension island": "🇦🇨",
    "pirate flag": "🏴‍☠️",
    "transgender flag": "🏳️‍⚧️",
    "rainbow flag": "🏳️‍🌈",
    "white flag": "🏳️",
    "black flag": "🏴",
    "crossed flags": "🎌",
    "triangular flag": "🚩",
    "chequered flag": "🏁"
}