const emojiDict = {
    "grinning face": "😀",
    "grinning face with big eyes": "😃",
    "grinning face with smiling eyes": "😄",
    "beaming face with smiling eyes": "😁",
    "grinning squinting face": "😆",
    "grinning face with sweat": "😅",
    "rolling on the floor laughing": "🤣",
    "face with tears of joy": "😂",
    "slightly smiling face": "🙂",
    "upside-down face": "🙃",
    "winking face": "😉",
    "smiling face with smiling eyes": "😊",
    "smiling face with halo": "😇",
    "smiling face with hearts": "🥰",
    "smiling face with heart-eyes": "😍",
    "star-struck": "🤩",
    "face blowing a kiss": "😘",
    "kissing face": "😗",
    "smiling face": "☺️",
    "kissing face with closed eyes": "😚",
    "kissing face with smiling eyes": "😙",
    "smiling face with tear": "🥲",
    "face savoring food": "😋",
    "face with tongue": "😛",
    "winking face with tongue": "😜",
    "zany face": "🤪",
    "squinting face with tongue": "😝",
    "money-mouth face": "🤑",
    "smiling face with open hands": "🤗",
    "face with hand over mouth": "🤭",
    "shushing face": "🤫",
    "thinking face": "🤔",
    "zipper-mouth face": "🤐",
    "face with raised eyebrow": "🤨",
    "neutral face": "😐",
    "expressionless face": "😑",
    "face without mouth": "😶",
    "face in clouds": "😶‍🌫️",
    "smirking face": "😏",
    "unamused face": "😒",
    "face with rolling eyes": "🙄",
    "grimacing face": "😬",
    "face exhaling": "😮‍💨",
    "lying face": "🤥",
    "relieved face": "😌",
    "pensive face": "😔",
    "sleepy face": "😪",
    "drooling face": "🤤",
    "sleeping face": "😴",
    "face with medical mask": "😷",
    "face with thermometer": "🤒",
    "face with head-bandage": "🤕",
    "nauseated face": "🤢",
    "face vomiting": "🤮",
    "sneezing face": "🤧",
    "hot face": "🥵",
    "cold face": "🥶",
    "woozy face": "🥴",
    "face with crossed-out eyes": "😵",
    "face with spiral eyes": "😵‍💫",
    "exploding head": "🤯",
    "cowboy hat face": "🤠",
    "partying face": "🥳",
    "disguised face": "🥸",
    "smiling face with sunglasses": "😎",
    "nerd face": "🤓",
    "face with monocle": "🧐",
    "confused face": "😕",
    "worried face": "😟",
    "slightly frowning face": "🙁",
    "frowning face": "☹️",
    "face with open mouth": "😮",
    "hushed face": "😯",
    "astonished face": "😲",
    "flushed face": "😳",
    "pleading face": "🥺",
    "frowning face with open mouth": "😦",
    "anguished face": "😧",
    "fearful face": "😨",
    "anxious face with sweat": "😰",
    "sad but relieved face": "😥",
    "crying face": "😢",
    "loudly crying face": "😭",
    "face screaming in fear": "😱",
    "confounded face": "😖",
    "persevering face": "😣",
    "disappointed face": "😞",
    "downcast face with sweat": "😓",
    "weary face": "😩",
    "tired face": "😫",
    "yawning face": "🥱",
    "face with steam from nose": "😤",
    "enraged face": "😡",
    "angry face": "😠",
    "face with symbols on mouth": "🤬",
    "smiling face with horns": "😈",
    "angry face with horns": "👿",
    "skull": "💀",
    "skull and crossbones": "☠️",
    "pile of poo": "💩",
    "clown face": "🤡",
    "ogre": "👹",
    "goblin": "👺",
    "ghost": "👻",
    "alien": "👽",
    "alien monster": "👾",
    "robot": "🤖",
    "grinning cat": "😺",
    "grinning cat with smiling eyes": "😸",
    "cat with tears of joy": "😹",
    "smiling cat with heart-eyes": "😻",
    "cat with wry smile": "😼",
    "kissing cat": "😽",
    "weary cat": "🙀",
    "crying cat": "😿",
    "pouting cat": "😾",
    "kiss mark": "💋",
    "waving hand": "👋",
    "raised back of hand": "🤚",
    "hand with fingers splayed": "🖐️",
    "raised hand": "✋",
    "vulcan salute": "🖖",
    "pinched fingers": "👌",
    "pinching hand": "🤏",
    "victory hand": "✌️",
    "crossed fingers": "🤞",
    "love-you gesture": "🤟",
    "sign of the horns": "🤘",
    "call me hand": "🤙",
    "backhand index pointing left": "👈",
    "backhand index pointing right": "👉",
    "backhand index pointing up": "👆",
    "middle finger": "🖕",
    "backhand index pointing down": "👇",
    "index pointing up": "☝️",
    "thumbs up": "👍",
    "thumbs down": "👎",
    "raised fist": "✊",
    "oncoming fist": "👊",
    "left-facing fist": "🤛",
    "right-facing fist": "🤜",
    "clapping hands": "👏",
    "raising hands": "🙌",
    "open hands": "👐",
    "palms up together": "🤲",
    "handshake": "🤝",
    "folded hands": "🙏",
    "writing hand": "✍️",
    "nail polish": "💅",
    "selfie": "🤳",
    "flexed biceps": "💪",
    "mechanical arm": "🦾",
    "mechanical leg": "🦿",
    "leg": "🦵",
    "foot": "🦶",
    "ear": "👂",
    "ear with hearing aid": "🦻",
    "nose": "👃",
    "brain": "🧠",
    "anatomical heart": "🫀",
    "lungs": "🫁",
    "tooth": "🦷",
    "bone": "🦴",
    "eyes": "👀",
    "eye": "👁️",
    "tongue": "👅",
    "mouth": "👄",
    "baby": "👶",
    "child": "🧒",
    "boy": "👦",
    "girl": "👧",
    "person": "🧑",
    "person: blond hair": "👱",
    "man": "👨",
    "person: beard": "🧔",
    "man: red hair": "👨‍🦰",
    "man: curly hair": "👨‍🦱",
    "man: white hair": "👨‍🦳",
    "man: bald": "👨‍🦲",
    "woman": "👩",
    "woman: red hair": "👩‍🦰",
    "person: red hair": "🧑‍🦰",
    "woman: curly hair": "👩‍🦱",
    "person: curly hair": "🧑‍🦱",
    "woman: white hair": "👩‍🦳",
    "person: white hair": "🧑‍🦳",
    "woman: bald": "👩‍🦲",
    "person: bald": "🧑‍🦲",
    "♀️ woman: blond hair": "👱",
    "♂️ man: blond hair": "👱",
    "older person": "🧓",
    "old man": "👴",
    "old woman": "👵",
    "person frowning": "🙍",
    "♂️ man frowning": "🙍",
    "♀️ woman frowning": "🙍",
    "person pouting": "🙎",
    "♂️ man pouting": "🙎",
    "♀️ woman pouting": "🙎",
    "person gesturing no": "🙅",
    "♂️ man gesturing no": "🙅",
    "♀️ woman gesturing no": "🙅",
    "person gesturing ok": "🙆",
    "♂️ man gesturing ok": "🙆",
    "♀️ woman gesturing ok": "🙆",
    "person tipping hand": "💁",
    "♂️ man tipping hand": "💁",
    "♀️ woman tipping hand": "💁",
    "person raising hand": "🙋",
    "♂️ man raising hand": "🙋",
    "♀️ woman raising hand": "🙋",
    "deaf person": "🧏",
    "♂️ deaf man": "🧏",
    "♀️ deaf woman": "🧏",
    "person bowing": "🙇",
    "♂️ man bowing": "🙇",
    "♀️ woman bowing": "🙇",
    "person facepalming": "🤦",
    "♂️ man facepalming": "🤦",
    "♀️ woman facepalming": "🤦",
    "person shrugging": "🤷",
    "♂️ man shrugging": "🤷",
    "♀️ woman shrugging": "🤷",
    "health worker": "🧑‍⚕️",
    "man health worker": "👨‍⚕️",
    "woman health worker": "👩‍⚕️",
    "student": "🧑‍🎓",
    "man student": "👨‍🎓",
    "woman student": "👩‍🎓",
    "teacher": "🧑‍🏫",
    "man teacher": "👨‍🏫",
    "woman teacher": "👩‍🏫",
    "judge": "🧑‍⚖️",
    "man judge": "👨‍⚖️",
    "woman judge": "👩‍⚖️",
    "farmer": "🧑‍🌾",
    "man farmer": "👨‍🌾",
    "woman farmer": "👩‍🌾",
    "cook": "🧑‍🍳",
    "man cook": "👨‍🍳",
    "woman cook": "👩‍🍳",
    "mechanic": "🧑‍🔧",
    "man mechanic": "👨‍🔧",
    "woman mechanic": "👩‍🔧",
    "factory worker": "🧑‍🏭",
    "man factory worker": "👨‍🏭",
    "woman factory worker": "👩‍🏭",
    "office worker": "🧑‍💼",
    "man office worker": "👨‍💼",
    "woman office worker": "👩‍💼",
    "scientist": "🧑‍🔬",
    "man scientist": "👨‍🔬",
    "woman scientist": "👩‍🔬",
    "technologist": "🧑‍💻",
    "man technologist": "👨‍💻",
    "woman technologist": "👩‍💻",
    "singer": "🧑‍🎤",
    "man singer": "👨‍🎤",
    "woman singer": "👩‍🎤",
    "artist": "🧑‍🎨",
    "man artist": "👨‍🎨",
    "woman artist": "👩‍🎨",
    "pilot": "🧑‍✈️",
    "man pilot": "👨‍✈️",
    "woman pilot": "👩‍✈️",
    "astronaut": "🧑‍🚀",
    "man astronaut": "👨‍🚀",
    "woman astronaut": "👩‍🚀",
    "firefighter": "🧑‍🚒",
    "man firefighter": "👨‍🚒",
    "woman firefighter": "👩‍🚒",
    "police officer": "👮",
    "man police officer": "👮‍♂️",
    "woman police officer": "👮‍♀️",
    "detective": "🕵️",
    "man detective": "🕵️‍♂️",
    "woman detective": "🕵️‍♀️",
    "guard": "💂",
    "man guard": "💂‍♂️",
    "woman guard": "💂‍♀️",
    "ninja": "🥷",
    "construction worker": "👷",
    "man construction worker": "👷‍♂️",
    "woman construction worker": "👷‍♀️",
    "prince": "🤴",
    "princess": "👸",
    "person wearing turban": "👳",
    "man wearing turban": "👳‍♂️",
    "woman wearing turban": "👳‍♀️",
    "person with skullcap": "👲",
    "woman with headscarf": "🧕",
    "person in tuxedo": "🤵",
    "man in tuxedo": "🤵‍♂️",
    "woman in tuxedo": "🤵‍♀️",
    "person with veil": "👰",
    "man with veil": "👰‍♂️",
    "woman with veil": "👰‍♀️",
    "pregnant woman": "🤰",
    "breast-feeding": "🤱",
    "woman feeding baby": "👩‍🍼",
    "man feeding baby": "👨‍🍼",
    "person feeding baby": "🧑‍🍼",
    "baby angel": "👼",
    "santa claus": "🎅",
    "mrs. claus": "🤶",
    "mx claus": "🧑‍🎄",
    "superhero": "🦸",
    "man superhero": "🦸‍♂️",
    "woman superhero": "🦸‍♀️",
    "supervillain": "🦹",
    "man supervillain": "🦹‍♂️",
    "woman supervillain": "🦹‍♀️",
    "mage": "🧙",
    "man mage": "🧙‍♂️",
    "woman mage": "🧙‍♀️",
    "fairy": "🧚",
    "man fairy": "🧚‍♂️",
    "woman fairy": "🧚‍♀️",
    "vampire": "🧛",
    "man vampire": "🧛‍♂️",
    "woman vampire": "🧛‍♀️",
    "merperson": "🧜",
    "merman": "🧜‍♂️",
    "mermaid": "🧜‍♀️",
    "elf": "🧝",
    "man elf": "🧝‍♂️",
    "woman elf": "🧝‍♀️",
    "genie": "🧞",
    "man genie": "🧞‍♂️",
    "woman genie": "🧞‍♀️",
    "zombie": "🧟",
    "man zombie": "🧟‍♂️",
    "woman zombie": "🧟‍♀️",
    "person getting massage": "💆",
    "man getting massage": "💆‍♂️",
    "woman getting massage": "💆‍♀️",
    "person getting haircut": "💇",
    "man getting haircut": "💇‍♂️",
    "woman getting haircut": "💇‍♀️",
    "person walking": "🚶",
    "man walking": "🚶‍♂️",
    "woman walking": "🚶‍♀️",
    "person standing": "🧍",
    "man standing": "🧍‍♂️",
    "woman standing": "🧍‍♀️",
    "person kneeling": "🧎",
    "man kneeling": "🧎‍♂️",
    "woman kneeling": "🧎‍♀️",
    "person with white cane": "🧑‍🦯",
    "man with white cane": "👨‍🦯",
    "woman with white cane": "👩‍🦯",
    "person in motorized wheelchair": "🧑‍🦼",
    "man in motorized wheelchair": "👨‍🦼",
    "woman in motorized wheelchair": "👩‍🦼",
    "person in manual wheelchair": "🧑‍🦽",
    "man in manual wheelchair": "👨‍🦽",
    "woman in manual wheelchair": "👩‍🦽",
    "person running": "🏃",
    "man running": "🏃‍♂️",
    "woman running": "🏃‍♀️",
    "woman dancing": "💃",
    "man dancing": "🕺",
    "person in suit levitating": "🕴️",
    "people with bunny ears": "👯",
    "men with bunny ears": "👯‍♂️",
    "women with bunny ears": "👯‍♀️",
    "person in steamy room": "🧖",
    "man in steamy room": "🧖‍♂️",
    "woman in steamy room": "🧖‍♀️",
    "person in lotus position": "🧘",
    "people holding hands": "🧑‍🤝‍🧑",
    "women holding hands": "👭",
    "woman and man holding hands": "👫",
    "men holding hands": "👬",
    "kiss": "💏",
    "kiss: woman, man": "👩‍❤️‍💋‍👨",
    "kiss: man, man": "👨‍❤️‍💋‍👨",
    "kiss: woman, woman": "👩‍❤️‍💋‍👩",
    "couple with heart": "💑",
    "couple with heart: woman, man": "👩‍❤️‍👨",
    "couple with heart: man, man": "👨‍❤️‍👨",
    "couple with heart: woman, woman": "👩‍❤️‍👩",
    "family": "👪",
    "family: man, woman, boy": "👨‍👩‍👦",
    "family: man, woman, girl": "👨‍👩‍👧",
    "family: man, woman, girl, boy": "👨‍👩‍👧‍👦",
    "family: man, woman, boy, boy": "👨‍👩‍👦‍👦",
    "family: man, woman, girl, girl": "👨‍👩‍👧‍👧",
    "family: man, man, boy": "👨‍👨‍👦",
    "family: man, man, girl": "👨‍👨‍👧",
    "family: man, man, girl, boy": "👨‍👨‍👧‍👦",
    "family: man, man, boy, boy": "👨‍👨‍👦‍👦",
    "family: man, man, girl, girl": "👨‍👨‍👧‍👧",
    "family: woman, woman, boy": "👩‍👩‍👦",
    "family: woman, woman, girl": "👩‍👩‍👧",
    "family: woman, woman, girl, boy": "👩‍👩‍👧‍👦",
    "family: woman, woman, boy, boy": "👩‍👩‍👦‍👦",
    "family: woman, woman, girl, girl": "👩‍👩‍👧‍👧",
    "family: man, boy": "👨‍👦",
    "family: man, boy, boy": "👨‍👦‍👦",
    "family: man, girl": "👨‍👧",
    "family: man, girl, boy": "👨‍👧‍👦",
    "family: man, girl, girl": "👨‍👧‍👧",
    "family: woman, boy": "👩‍👦",
    "family: woman, boy, boy": "👩‍👦‍👦",
    "family: woman, girl": "👩‍👧",
    "family: woman, girl, boy": "👩‍👧‍👦",
    "family: woman, girl, girl": "👩‍👧‍👧",
    "speaking head": "🗣️",
    "bust in silhouette": "👤",
    "busts in silhouette": "👥",
    "people hugging": "🫂",
    "footprints": "👣",
    "luggage": "🧳",
    "closed umbrella": "🌂",
    "umbrella": "☂️",
    "jack-o-lantern": "🎃",
    "thread": "🧵",
    "yarn": "🧶",
    "glasses": "👓",
    "sunglasses": "🕶️",
    "goggles": "🥽",
    "lab coat": "🥼",
    "safety vest": "🦺",
    "necktie": "👔",
    "t-shirt": "👕",
    "jeans": "👖",
    "scarf": "🧣",
    "gloves": "🧤",
    "coat": "🧥",
    "socks": "🧦",
    "dress": "👗",
    "kimono": "👘",
    "sari": "🥻",
    "one-piece swimsuit": "🩱",
    "briefs": "🩲",
    "shorts": "🩳",
    "bikini": "👙",
    "woman’s clothes": "👚",
    "purse": "👛",
    "handbag": "👜",
    "clutch bag": "👝",
    "backpack": "🎒",
    "thong sandal": "🩴",
    "man’s shoe": "👞",
    "running shoe": "👟",
    "hiking boot": "🥾",
    "flat shoe": "🥿",
    "high-heeled shoe": "👠",
    "woman’s sandal": "👡",
    "ballet shoes": "🩰",
    "woman’s boot": "👢",
    "crown": "👑",
    "woman’s hat": "👒",
    "top hat": "🎩",
    "graduation cap": "🎓",
    "billed cap": "🧢",
    "military helmet": "🪖",
    "rescue worker’s helmet": "⛑️",
    "lipstick": "💄",
    "ring": "💍",
    "briefcase": "💼",
    "drop of blood": "🩸"
}

let memory = {};

class EmojiSearch {
    static getMatches(query) {
        if (memory[query]) return memory[query];
        let oneCharLessMatches = memory[query.substring(0, query.length-1)];
        if (query.length > 1 && oneCharLessMatches && oneCharLessMatches.length === 0) {
            memory[query] = [];
            return [];
        }
        let matches = [];
        Object.keys(emojiDict).forEach((key) => {
            if (key.includes(query)) {
                matches.push(emojiDict[key]);
            }
        });
        memory[query] = matches;
        return matches;
    }
}